# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Pulpit/ZynQ/RLC_Z/RLC_Z.srcs/sources_1/bd/rlc_design/ip/rlc_design_xbar_0/rlc_design_xbar_0.xci
# IP: The module: 'rlc_design_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Pulpit/ZynQ/RLC_Z/RLC_Z.srcs/sources_1/bd/rlc_design/ip/rlc_design_xbar_0/rlc_design_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rlc_design_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Pulpit/ZynQ/RLC_Z/RLC_Z.srcs/sources_1/bd/rlc_design/ip/rlc_design_xbar_0/rlc_design_xbar_0.xci
# IP: The module: 'rlc_design_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Pulpit/ZynQ/RLC_Z/RLC_Z.srcs/sources_1/bd/rlc_design/ip/rlc_design_xbar_0/rlc_design_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rlc_design_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
