# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/rlc_design/rlc_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rlc_design || ORIG_REF_NAME==rlc_design} -quiet] -quiet

# IP: bd/rlc_design/ip/rlc_design_processing_system7_0_0/rlc_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rlc_design_processing_system7_0_0 || ORIG_REF_NAME==rlc_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/rlc_design/ip/rlc_design_coder_ip_0_0/rlc_design_coder_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rlc_design_coder_ip_0_0 || ORIG_REF_NAME==rlc_design_coder_ip_0_0} -quiet] -quiet

# IP: bd/rlc_design/ip/rlc_design_decoder_ip_0_0/rlc_design_decoder_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rlc_design_decoder_ip_0_0 || ORIG_REF_NAME==rlc_design_decoder_ip_0_0} -quiet] -quiet

# IP: bd/rlc_design/ip/rlc_design_xbar_0/rlc_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rlc_design_xbar_0 || ORIG_REF_NAME==rlc_design_xbar_0} -quiet] -quiet

# IP: bd/rlc_design/ip/rlc_design_ps7_0_axi_periph_0/rlc_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rlc_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==rlc_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/rlc_design/ip/rlc_design_rst_ps7_0_100M_0/rlc_design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rlc_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==rlc_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/rlc_design/ip/rlc_design_auto_pc_0/rlc_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rlc_design_auto_pc_0 || ORIG_REF_NAME==rlc_design_auto_pc_0} -quiet] -quiet

# XDC: bd/rlc_design/rlc_design_ooc.xdc
